version: '3.4'

services:
  eshopdb:
    container_name: eshopdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssword1
      POSTGRES_DB: EShopDb
    restart: always
    ports:
      - "1234:5432"
    volumes:
      - postgres_eshopdb:/var/lib/postgresql/data/

  seq:
    container_name: seq
    ports:
      - "5341:5341"
      - "9091:80"
    environment:
      - ACCEPT_EULA=Y
    restart: always
